#!/bin/sh

python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.2 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.2 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.2 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.4 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.4 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.4 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.6 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.6 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.6 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.8 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.8 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0 --rand_action_p 0.8 --BCQ_threshold 0.7

python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.2 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.2 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.2 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.4 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.4 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.4 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.6 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.6 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.6 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.8 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.8 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.2 --rand_action_p 0.8 --BCQ_threshold 0.7

python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.2 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.2 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.2 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.4 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.4 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.4 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.6 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.6 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.6 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.8 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.8 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.4 --rand_action_p 0.8 --BCQ_threshold 0.7

python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.2 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.2 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.2 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.4 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.4 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.4 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.6 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.6 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.6 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.8 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.8 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.6 --rand_action_p 0.8 --BCQ_threshold 0.7

python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.2 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.2 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.2 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.4 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.4 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.4 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.6 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.6 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.6 --BCQ_threshold 0.7
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.8 --BCQ_threshold 0.3
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.8 --BCQ_threshold 0.5
python main.py --env MiniGrid-DoorKey-8x8-v0 --low_noise_p 0.8 --rand_action_p 0.8 --BCQ_threshold 0.7